artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: #put gdrive link here
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir:  artifacts/data_ingestion 